### ISSUE TITLE
Specify files to ignore

### ISSUE THREAD

**Issue by MyNameIsOka** [aws-actions/codeguru-security#5]
Hi community,

is there a way to specify files which should be ignored and not checked?

I found resources speaking about CodeGuru Reviewer but not CodeGuru Security.

**Comment by vineetdpnd** [comment]
We need the same as well. Were you able to figure it out @MyNameIsOka  ?

**Comment by ThomasBalfour** [comment]
Workaround for this:

Let’s say you want to exclude the following directories or files:

- www/lib
- src/generated
- tests/helpers/mockData.ts
- docs/temp

You would set up an rsync step to make a new directory, in this case "filtered-src" then rsync the source to the new folder excluding the ones you don't want:

```
- name: Prepare source excluding specific files and folders
  run: |
    mkdir filtered-src
    rsync -av \
      --exclude='www/lib' \
      --exclude='src/generated' \
      --exclude='tests/helpers/mockData.ts' \
      --exclude='docs/temp' \
      ./ filtered-src/
```

Notes:
Each --exclude matches a relative path from the root of the repo.
Paths with forward slashes (/) are recommended for cross-platform consistency.
You can also use wildcards like --exclude='**/node_modules' to match patterns recursively.

You then update your source-path in the Codeguru analysis step to point to your rsynced folder:

```
      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: filtered-src
          aws_region: eu-west-2
```
